version: '3.8'
services:
    php-apache-environment:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: cuvee
        image: php:8.1-apache
        hostname: localhost
        volumes:
            - ./:/var/www/html/
            - ./.docker/php/php.ini-development:/usr/local/etc/php/php.ini-development
            - ./.docker/php/ini/conf.d/memory_limit.ini:/usr/local/etc/php/ini/conf.d/memory_limit.ini
            - ./.docker/mysql/my.cnf:/usr/local/etc/mysql/my.cnf
#            - ./.docker/php/ini:/usr/local/etc/php
#            - ./.docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - 8000:80
    db:
        platform: linux/x86_64
        container_name: db_cuvee
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cuvee
            MYSQL_PASSWORD: root
        ports:
            - "9907:3306"
        command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT=100000000
    composer:
        image: composer



